AWSTemplateFormatVersion: '2010-09-09'
Description: Template for creation of Lambda Function used for German Word a Day

Parameters:
  Input_File:
    Type: String
    Description: File name that will be stored as an environment variable
  Input_Bucket:
    Type: String
    Description: Bucket name that will be stored as an environment variable
  Sender_Email:
    Type: String
    Description: Email address that will be stored as an environment variable 

Resources:
  ProvisionLambdaFunction:
    Type: AWS::Lambda::Function
    Properties: 
      Code: 
        S3Bucket: serverless-german-word-a-day
        S3Key: 
      DeadLetterConfig: 
        DeadLetterConfig
      Description: German Word A Day Lambda Function that selects and emails out word from vocab list
      Environment: 
        Variables:
          - german_dict: !Ref Input_File
          - input_bucket: !Ref Input_Bucket
          - sender_email: !Ref Sender_Email
      FunctionName: German-Word-A-Day-Lambda
      Handler: index.handler
      MemorySize: 128
      PackageType: Zip
      Role: arn:aws:iam::285745372420:role/service-role/German_Word_a_Day-role-u8ocl8ie
      Runtime: python3.9
      Tags: 
        - Key: "Project"
        Value: "German Word a Day"
      Timeout: 5